title: Brand
strapline: 'Help! We’re really good at what we do but nobody knows'
author: 44ff6e56-6b78-49e2-a074-616caf791879
updated_by: 44ff6e56-6b78-49e2-a074-616caf791879
updated_at: 1611247486
blueprint: core-services
tag_line_us: 'Build a brand that makes you stand out'
tag_line_you: 'You need a distinctive brand'
template: service-taxonomy/show
introduction: 'It’s bonkers to spend a tonne of cash on beautifully crafted marketing, only to find out it looks exactly the same as your competitors. That’s why we always look at your problem from a new angle, so we can give you that little something you didn’t realise you needed.'
hero_image: 9-ParkingEye.jpg
grid:
  -
    title: Strategy
    text: '“The possibilities are endless!” When you’re stood at the dessert buffet they’re the best words in the world. When you’re thinking about your brand and marketing? Not so much. Because branding needs focus. Purpose. Direction. Your branding needs strategy. And this is where you find it.'
    bold_text: 'Set your direction'
    bottom_text: |
      Sure, you could spend the rest of your life throwing marketing ideas at the wall and seeing what sticks, but you probably don’t have time for that. You definitely won’t have the budget for that.
      
      That’s why you need a strategy. It’s how you identify what really matters. Before the creatives start doing their whizzy stuff, a strategy is how you can be confident that a) this will have an impact and b) it will have the impact you actually want. 
      
      The possibilities are endless. So let’s start whittling them down to the ones that can really make a difference with a clear, smart and simple strategy. Here’s how...
  -
    title: 'Research & Insights'
    text: '“Research is creating new knowledge”. Neil Armstrong said that, which just goes to show there was a good career in marketing waiting for him if he ever grew tired of the astronaut stuff. But what new knowledge do you need?'
    bold_text: 'Knowledge. Not assumptions.'
    bottom_text: |
      At Think! Creative, research doesn’t come freeze dried and prepacked (unlike Neil’s lunch). We don’t start with the answers and design a survey to conveniently arrive at what we thought in the first place. 
      
      With us, you’ll find fresh insights that confirm your suspicions or data. You’ll find insights that contradict the conventional wisdom. And you’ll find the occasional answer that raises questions you simply never thought of before. Often, those can be the most rewarding insights of all. As the foundations of a new brand strategy or simply because it’s good to have actual knowledge rather than assumptions, when you need to ask...
      
      - What do your customers think?
      - What do the people who aren’t (yet) your customers think? 
      - What are your competitors doing?
      - How well known are you?
      - How are perceptions of your brand/business changing over time? 
      
      
      ... ask us to find out.
