title: Strategy
content: 'Help! We’re not sure what will work best'
strapline: 'Help! We’re not sure what will work best'
author: 44ff6e56-6b78-49e2-a074-616caf791879
updated_by: 44ff6e56-6b78-49e2-a074-616caf791879
updated_at: 1599836416
# blueprint: services_level
blueprint: core-services
tag_line_us: 'You know exactly what you need to do to succeed'
tag_line_you: 'You need a strategy'
template: service-taxonomy/show