title: Service
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: hero
  top_layered_block:
    display: 'Top Layered Block'
    fields:
      -
        import: layered_block
  below_layered_block:
    display: 'Below Layered Block'
    fields:
      -
        import: call_to_action
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: handle_text
        field:
          input_type: text
          antlers: false
          display: 'Handle Text'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: handle_link
        field:
          display: 'Handle Link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
      -
        handle: bouncing_arrow
        field:
          default: false
          display: 'Bouncing Arrow'
          type: toggle
          icon: toggle
          instructions: 'Shows a bouncing arrow at the bottom of the hero.'
          listable: hidden
          instructions_position: above
  SEO:
    display: SEO
    fields:
      -
        handle: seo
        field:
          type: seo_pro
          listable: false
          display: SEO
