title: Service
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: hero
  top_layered_block:
    display: 'Top Layered Block'
    fields:
      -
        import: layered_block
  below_layered_block:
    display: 'Below Layered Block'
    fields:
      -
        import: call_to_action
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
  SEO:
    display: SEO
    fields:
      -
        handle: seo
        field:
          type: seo_pro
          listable: false
          display: SEO
