title: Activations
video_choice: Video
video: /assets/heros/service/sprinkles.mp4
service_tag: '30 flavours of creative'
grid:
  -
    title: Activation
    text: 'You have a brand. But now, what are you going to do with it? Let’s lick it into shape.'
    bold_text: '30 flavours of creative'
    bottom_text: |-
      At first glance, creative agencies are a bit like those bags of misshaped chocolates you find at retail outlets. Until you rip off the wrapper, you’re never entirely sure what’s inside. Will it be a magic mix of skills, or will it be half a dozen graphic designers who all do much the same thing?

      The Think!Creative team is a wonderful mix of flavours (without any of the strawberry creams no one likes) with serious brand building as our core ingredient. That means we can take your brand in loads of different directions, with all the skills you need all in one place. You can put all our talents to work. Or you can cherry-pick the ones you don’t already have in-house – we’re easy.

      From the website to product packaging to the expo stand and even the walls of your office, we can (literally) take your brand further and make it work harder without you needing to do anything other than have a chat with us.

      Now that takes some licking.
    coll_image: null
  -
    title: 'Web Design & Development'
    text: 'Let’s leave aside the bells and whistles for a minute. When you get down to it, your website just needs to work. Simply.'
    bold_text: 'Websites slicker than a greased otter'
    bottom_text: |-
      We’re betting this isn’t your first website. Chances are you’ve been down this road before. Of course you have, trends and tech change and you don’t want your website to look like it crawled out of 1999.

      But beyond a funky surface makeover (and we promise yours will look very funky indeed), there’s a bigger issue to address. In the years since your last website was built, your business has changed. Your brand has developed. And your customers have learned to expect more.

      Maybe you didn’t need eCommerce before, but now you do. Perhaps you only updated your content once in a blue moon, but now you do it more often so you need it to be quick and easy. Perhaps customers tell you things aren’t where they expect to find them.

      So let’s fix that. Yes, your new site will show your brand at its best. But under the bonnet it’ll run slicker than a greased otter and purr like a happy cat - which will make you and your customers happy too.
    coll_image: null
  -
    title: Copywriting
    text: |-
      "The secret of being boring is to say everything". Voltaire said that, and we promise that’s the first and last time we’ll quote a French philosopher. But he was right. You see, great copywriting isn’t just about finding the right words. It’s about knowing when to shut up.   

      So let’s get it right. And write.
    bold_text: 'Want a word?'
    bottom_text: |-
      A product description. A Facebook ad. A blog post or press release. They all need words. But even though they all come from the same brand, the words need to be very different. 
      Sometimes it’s about telling a story. Sometimes it’s about the technical details. Sometimes it’s just about the ‘buy now’ or the ‘add to cart’. 

      When you have a brand to look after, every word needs to be tailored not just to the specific purpose and the reader. It needs to stay true to the brand too. Most importantly, your words need to not only encourage readers to keep reading. They need to make them click, like, buy, call or message. 

      And then they need to stop before they outstay their welcome.

      That’s what our copywriters’ words do.
    coll_image: null
  -
    title: 'Creative Design'
    text: 'A wry smile. A nod of appreciation. A chuckle to no one in particular. That’s when you know your little moment of ‘wow’ has made an impact. That’s when you know they’ll remember you.'
    bold_text: 'Big ideas. Little moments'
    bottom_text: |-
      Mail’s arrived. On your desk right now are some brown envelopes you really don’t want to open, the odd brochure, and a bit of junk mail that may as well have ‘bin’ written in big letters on it. Your inbox and social feeds are the same. Lots of offers you skip. Lots of ads you ignore. 

      But what’s this? Something clever. Something that makes you laugh or say, ‘I’ve never seen that before’. Something that gets your fingers tapping, clicking or unfolding. 

      That’s the result we’re after. It’s the ad that grabs. It’s the poster or banner on the bus stop, bridge or building. It’s the box you package your products in that’s says, ‘this really is worth paying a premium for’. 

      It’s the big ideas that produce the little moments that create the great impressions.

      That’s Creative Design at Think!Creative.
    coll_image: null
  -
    title: 'Film & Animation'
    text: 'We make movies for business. Perhaps more importantly, we make making movies for business simple.'
    bold_text: 'Branding in motion'
    bottom_text: |-
      "Wouldn’t it be great," someone says in the meeting, "if we could do a short movie about this? We could have an animated character and everything. It’ll be brilliant."

      The thing is, it really could be brilliant. A movie – animated or not – is great for holding the attention in a way 300 words or a 300 slide PowerPoint deck never could. It engages. It drives likes, shares and all the other things you’ll be focused on if you’re doing a social campaign. And when you want your product or business to make a big impression, that combination of motion, sound and story sells your brand like nothing else.  

      But how do you turn a big idea into an actual movie? Where do you even start with something like that? And when the finished product relies on so many different elements coming together – animation, music, script, voiceover – who do you get to manage all that for you?

      That would be us...
    coll_image: null
  -
    title: Illustration
    text: '''Show not tell''. ''A picture is worth a thousand words''. ''An illustration is visual editorial''. Yes they’re whopping great cliches. But they also happen to be true.'
    bold_text: 'Start making sense'
    bottom_text: |-
      You’re building an IKEA bookshelf and, despite the fact you’re pretty rubbish at self-assembly, the instructions make it easy. Or maybe you’re sat on the plane looking at the aircraft safety card and, no matter what language you speak, you understand where the exits are, where the life jacket is and what to do with that pointless whistle.

      In these and bucketloads of other situations, words are no good. Words would just get in the way or leave you more confused than when you started. But an illustration? Now you’re talking. Or, to put it another way, now you’re showing.

      A great illustration just makes sense.

      Let us show you how.
    coll_image: null
  -
    title: '3D Design'
    text: '2D could do the job. 3D will make the difference. Because 3D brings visions to life.'
    bold_text: 'Possibilities from every angle'
    bottom_text: |-
      You make extremely cool stuff that comes in lots of shapes, sizes and colour options. You could take a shot of every single one. In every possible setting. From every angle and in every combination. But by the time you’ve finished it’ll be 2050 and your photographer will be old and (probably) very rich. Let’s speed things up a bit.

      3D design is about flexibility and possibilities. It’s about seeing what that sofa could look like in any of 100 different fabrics without needing the sofa or the fabric to exist just yet. It’s the apartment you can take a digital walk through before a brick has been laid. It’s taking a 360° tour of the shirt, car, necklace or literally anything else.

      That’s great for eCommerce. But it could also make your app appeal, your promo video pop or the expo explode.

      Give your audience an experience worth talking about. Let’s talk about yours.
    coll_image: null
  -
    title: 'Branded Environments'
    text: 'A great brand shouldn’t be tied up or chained down. A 4" screen can’t contain it. So let’s turn your branding up to 11 and really let it loose. Here’s how.'
    bold_text: 'The writing’s on the wall'
    bottom_text: |-
      Branding is about finding that big idea and bringing it to life. Sometimes, that demands a really big canvas. That might be an obvious thing to do if you run a retail store, hotel, airline or restaurant. But what about the office reception area? The boardroom? The workspace? 

      Branding the environment isn’t just POS, signage and exhibition stands (although we do those too). It’s walls and doors, windows and lifts, wall art and foyer installations. It’s not just living with the brand; it’s living in it. And it’s a fantastically powerful way of making sure that, every step your staff, guests or customers take, your brand stays with them.

      Of course, that will look amazing. But there’s much more to it than that. It’s about making people feel part of something. About team spirit. About attracting and keeping hold of the best talent who prefer your space to the land of grey cubicles down the road.

      It’s about helping people love what they do more, by loving where they are.
    coll_image: null
strapline: 'Help! People can’t tell us apart from the competition'
tag_line_us: 'A consistent journey. Tell your story across every single one of your brand touchpoints.'
tag_line_you: 'You need experience'
template: service-taxonomy/show
v2_service_title: Activations
v2_service_content: 'From the website to product packaging to the expo stand and even the walls of your office, we can (literally) take your brand further and make it work harder without you needing to do anything other than have a chat with us.'
v2_left_list:
  - 'Print & Digital Design'
  - Copywriting
  - Animation
  - 'Packaging Design'
v2_right_list:
  - 'Branded Spaces'
  - Exhibitions
  - 'Website Design'
  - 'Web Development'
v2_service_image:
  - service-thumbnail/Services-Activation.jpg
v2_service_button_label: 'Read More'
updated_by: e85953fb-52c6-4488-8c8b-c90f68b2bb10
updated_at: 1644577446
blueprint: core
hero_text: Activations
hero_intro: 'You have a brand. But now, what are you going to do with it? Let’s lick it into shape.'
content_grid:
  -
    content_title: 'Creative Design'
    content_text: 'When you get down to it, design needs to turn insights into action and ideas into reality. But beyond a funky surface makeover (and we promise your stuff will look very funky indeed), creative design is about going further. It’s about giving people a wry smile. A nod of appreciation. A chuckle to no one in particular. That’s when you know your little moment of ‘wow’ has made an impact. That’s when you know they’ll remember you. From digital to print, websites to brochures, to expo stands and even the walls of your office, we can (literally) take your brand further and make it work harder without you needing to do anything other than call us.'
    content_image: service-thumbnail/Services-Activations-Creative-Design.jpg
    content_link_text: 'Let''s get creative'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: 'Film & Animation'
    content_text: '“Wouldn’t it be great,” someone says in the meeting, “if we could do a short movie about this? We could have an animated character and everything. It’ll be brilliant.” The thing is, it really could be brilliant. A movie – animated or not – is great for holding the attention in a way 300 words or a 300 slide PowerPoint deck never could. It engages. It drives likes, shares and all the other things you’ll be focused on if you’re doing a social campaign. And when you want your product or business to make a big impression, that combination of motion, sound and story sells your brand like nothing else.  But who do you get to turn a big idea into an actual movie? That would be us…'
    content_image: service-thumbnail/Services-Activations-Animation.jpg
    content_link_text: 'Put your brand in motion'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: 'Branded Spaces'
    content_text: 'Branding is about finding that big idea and bringing it to life. Sometimes, that demands a really big canvas. That might be an obvious thing to do if you run a retail store, hotel, airline or restaurant. But what about the office reception area? The boardroom? The workspace? Branding the environment isn’t just POS, signage and exhibition stands (although we do those too). It’s walls and doors, windows and lifts, wall art and foyer installations. And it’s a fantastically powerful way of making sure that, every step your staff, guests or customers take, your brand stays with them. A great brand shouldn’t be tied up or chained down. A 4” screen can’t contain it. So let’s turn your branding up to 11 and really let it loose.'
    content_image: service-thumbnail/Services-Activations-Branded-Spaces.jpg
    content_link_text: 'The writing’s on the wall'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: Illustration
    content_text: 'You’re building an IKEA bookshelf and, despite the fact you’re pretty rubbish at self-assembly, the instructions make it easy. Or maybe you’re sat on the plane looking at the aircraft safety card and, no matter what language you speak, you understand where the exits are, where the life jacket is and what to do with that pointless whistle. In these and bucketloads of other situations, words are no good. Words would just get in the way or leave you more confused than when you started. But an illustration? Now you’re talking. Or, to put it another way, now you’re showing.A great illustration just makes sense. Let us show you how.'
    content_image: service-thumbnail/Services-Activations-Illustration.jpg
    content_link_text: 'Tell your story with illustration'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: '3D Design'
    content_text: 'You make extremely cool stuff that comes in lots of shapes, sizes and colour options. You could take a shot of every single one. In every possible setting. From every angle and in every combination. But by the time you’ve finished it’ll be 2050 and your photographer will be old and (probably) very rich. Let’s speed things up a bit. 3D design is about flexibility and possibilities. It’s about seeing what that sofa could look like in any of 100 different fabrics without needing the sofa or the fabric to exist just yet. That’s great for eCommerce. But it could also make your app appeal, your promo video pop or the expo explode. 2D could do the job. 3D will make the difference.'
    content_image: service-thumbnail/Services-Activations-3D-Design.jpg
    content_link_text: 'Possibilities from every angle'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: Copywriting
    content_text: '“The secret of being boring is to say everything”. Voltaire said that, and we promise that’s the first and last time we’ll quote a French philosopher. But he was right. Great copywriting isn’t just about finding the right words. It’s about knowing when to shut up.  Sometimes it’s about telling a story. Sometimes it’s about the technical details. Sometimes it’s just about the ‘buy now’ or the ‘add to cart’. Most importantly, your words need to not only encourage readers to keep reading. They need to make them click, like, buy, call or message. And then they need to stop before they outstay their welcome. So let’s get it right. And write.'
    content_image: service-thumbnail/Services-Activations-Copywriting.jpg
    content_link_text: 'Want a word? Let''s talk'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
call_to_action: 'Got a creative project coming up? Tell us about it today!'
handle_text: 'Let’s Think! together'
where_do_i_go: 3
cta_button: 'Contact us'
cta_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
