title: Brand
strapline: 'Help! We’re really good at what we do but nobody knows'
author: 44ff6e56-6b78-49e2-a074-616caf791879
updated_by: 35c7384a-60a0-4933-9645-d8850117c385
updated_at: 1637243109
blueprint: core
tag_line_us: 'It''s all in the story. Build or refresh your brand so you look the business and do the business.'
tag_line_you: 'You need a distinctive brand'
template: service-taxonomy/show
introduction: 'It’s bonkers to spend a tonne of cash on beautifully crafted marketing, only to find out it looks exactly the same as your competitors. That’s why we always look at your problem from a new angle, so we can give you that little something you didn’t realise you needed.'
hero_image: 9-ParkingEye.jpg
grid:
  -
    title: 'Brand Identity'
    text: |-
      Know what? Your brand doesn’t live where you think it does. It doesn’t live on the website. It’s not in the social media channel, brochure or online ad. Done right, your brand lives in the head of everyone who knows you. Done wrong it…er… doesn’t.

      Let’s do your brand identity right.
    bold_text: 'What’s the big idea?'
    bottom_text: |-
      You’ve got a strategy. Now you need a brand identity to match. But what does that mean? Well, let’s put it like this. It’s the stuff that makes you, you. It’s your visual (and increasingly, audio) DNA. 

      Yes, it includes your logo, but it’s so much more than that. It’s the type and tone of the words your business uses when it talks to people. It’s the colours that really work (imagine if the McDonalds golden arches weren’t golden). It’s the ‘ding’ or whoosh’ that tells everyone who hears it that it’s you (think the ‘da-dum oooohhhhh’ when you load up Netflix). It’s words, pictures and sounds. 

      Wrangling all that gets a lot easier when it all fits around one big idea. All the biggest and best brands have a core idea around which everything else sits. So we take a deep plunge into your brand strategy to find yours. Then, we bring it to life.
      Let’s get started.
    coll_image: null
  -
    title: 'Brand Identity Creation'
    text: 'New. Pre-loved. A bit of a mess. Wherever you’re at with your brand identity, we’re ready to give it a creative shot in the arm.'
    bold_text: 'Brand spanking?'
    bottom_text: |-
      New is always exciting isn’t it? And if you’re a business discovering your brand identity for the first time, we promise to make it one very happy ride. 

      But here’s a thought. Perhaps you don’t need a new brand identity. Perhaps you just need to give the old one a new lick of paint and a damn good polish to make it sparkle again. We can do that.

      Or perhaps things have changed. Once, your brand was so hot it sizzled. Now it’s a bit cringey, like dad dancing or that time Gal Gadot and friends decided singing Imagine (badly) would make the world a better place.

      That’s the time to get back to your brand strategy, look again at what works, boot out anything that doesn’t and replace it with just the good stuff.

      Let’s talk about how we do that now.
    coll_image: null
  -
    title: 'Brand & Product Naming'
    text: 'If you need to explain it, repeat it or get a flipchart out and draw diagrams about it, your brand or product name probably doesn’t work. So let’s create names that need no explanation...'
    bold_text: 'A name to remember'
    bottom_text: |-
      The Big Mac started life as The Aristocrat. Google was once BackRub. Vaseline started out as Wonder Jelly. Which is kind of terrifying. 

      A great brand or product name needs to be simple to say, spell and remember. Which is just one reason why IBM probably didn’t sell too many computers back when they were the Computing Tabulating Recording Corporation.

      So how do we create a product name that really works rather than making you shudder (hello again, Wonder Jelly)? Well, part of it can be the legwork of surveys and market research. But much of it is down to the fact that we’ve been doing this a really long time and we back the science with experience and loads of industry knowledge.

      Also, we’re so excited to be the people who help put a name to what you do.
    coll_image: null
  -
    title: 'Brand Guardians'
    text: 'You’ve already got a brilliant brand. So what you need from your creative team is the ability to take it in exciting new directions whilst protecting everything that made it so great in the first place. You need brand guardians. That’s us. We’ve had spandex suits made and everything…'
    bold_text: 'Your brand’s big brother'
    bottom_text: |-
      Having a brand that everyone knows and loves is a big advantage – so why would you mess with that? Great brands don’t need revolution. But they do need creatives who are happy to stand on the shoulders of those who went before them, creatives who’ll take what has always worked well and make it work even better. 

      We do that. But that’s not all we do, because a brand needs people on its side. So we work with you to make sure your team ‘gets it’, sharing our enthusiasm for it, so they can do the same with the people who really matter: your customers.

      Being a brand guardian is a responsibility. It’s a challenge. And if yours is a brand that has been around forever, it’s an honour to be its big brother for a while. 
      Got a brand you’re proud of? Let us run with it.
    coll_image: null
  -
    title: 'Messaging & Tone of Voice'
    text: 'Hello. Hi. Hey! Wazzuuup? It’s funny isn’t it? Just by changing the one word you choose to greet people, you can completely change their perception of you. Imagine the difference the rest of what you say can make.'
    bold_text: null
    bottom_text: null
    coll_image: null
  -
    title: Words-worth
    text: 'You must have seen them: two people squashed together on the underground trying hard not to look, touch or acknowledge one another.'
    bold_text: 'Awkward. Your brand’s words and pictures shouldn’t be like that.'
    bottom_text: |-
      They should be a great partnership: Lennon and McCartney. Ant and Dec. Tess & Claudia. Individually they can be good. Together they can be Strictly, tangoing up fab-u-lous reactions.

      That’s the value of getting the messaging and the tone of voice right. Because it’s not just what you say that matters. It’s not even purely about how you say it. It’s about finding a voice that’s uniquely yours - that fits your brand, every situation and every customer - and that helps you do that simplest (but most important) of things: connect.
    coll_image: null
video_choice: Image
v2_service_title: Brand
v2_service_content: 'Know what? Your brand doesn’t live where you think it does. It doesn’t live on the website. It’s not in the social media channel, brochure or online ad. Done right, your brand lives in the head of everyone who knows you. Done wrong it…er… doesn’t. Let’s do your brand right.'
v2_left_list:
  - 'Brand Identity'
  - 'Messaging & Tone'
  - 'Brand Audits'
  - Naming
v2_right_list:
  - 'Brand Guardians'
  - 'Touchpoint Activations'
  - Training
  - 'Brand Audits'
v2_service_image:
  - 3-BAE.jpg
v2_service_button_label: 'Click Here'
