route: core-services/testing
title: Campaign
content: 'Help! We’re really good at what we do but nobody knows'
strapline: 'Help! We’re really good at what we do but nobody knows'
updated_by: 6fb67458-0db4-428c-8f86-8445dcb283dc
updated_at: 1644326715
blueprint: core
tag_line_us: 'Get noticed. Simple. Spark imaginations and create conversations in print, digital and beyond.'
tag_line_you: 'You need a campaign'
template: service-taxonomy/show
grid:
  -
    title: Campaign
    text: 'Let’s not be delicate about it, selling is what a marketing campaign is designed to do. And when the world is this bloomin’ noisy, that’s no mean feat. So how are you going to do it?'
    bold_text: 'Buy. Sell. Seduce.'
    bottom_text: |-
      Well, one way is to make friends with your customer. Engage them. Inform them. Seduce them if you like, you saucy thing. It’s about making them feel good about your brand by making them feel good about themselves.

      The other is to deliver a punch like Nicola Adams and a punchline like Jimmy Carr, a message you can’t miss because a) it’s a damn good message and b) you can’t help but see it everywhere you look.

      The funny thing is that whilst both approaches can work brilliantly, they can work even better when you do both.

      Discover how.
    coll_image: null
  -
    title: 'Integrated campaigns'
    text: |-
      Last night, within about 30 minutes, you watched a bit of TV, checked your phone’s news feed, watched a cat video your mum sent you and searched for a birthday present for your brother. Ok, so that may not be 100% accurate. It may have been a dog video, but you get the gist. 

      Our point is this: how the hell are you supposed to grab the attention span of customers who don’t have one?
    bold_text: 'Attention please.'
    bottom_text: |-
      When no one is focused on anything for too long you can’t expect one ad in one place to hit home. So if you want to make a big noise, it’s not just what you say and how you say it. It’s where you say it that counts.

      That’s the beauty of an integrated campaign with Think!. Yes, your ad zings like a lemon on steroids, but it also targets your customers like a sniper and zeroes in on them wherever they are – online, in print, in app or by email.

      And the more impressions you make, the more of an...er... impression you make.

      Grab their attention. Start by grabbing ours.
    coll_image: null
  -
    title: 'Brand Advertising'
    text: 'Your brand has the power to stir the emotions, to stimulate the feels and to take up residence in your customers’ heads. And there’s you thinking you just made ‘stuff’. Tch.'
    bold_text: 'Brand aware?'
    bottom_text: |-
      We promise not to get all nerdy about this, but there are two types of campaign. One is the short term, ‘here’s our product/service, buy it now’ sort of campaign. We do those and you’ll find them here.

      But the other doesn’t have a specific product in mind. It’s a slower burn, designed to let your brand drip, drip, drip into the memory. Take Apple. Sometimes they’ll run a campaign advertising the latest iPhone. But sometimes they’ll run a campaign that has no ambition other than to make you think ‘wow, Apple’.

      How do they do that? They do it by sharing values. By tapping into deep emotion. By making you feel.

      We’d like to show you how that could work for your brand.
    coll_image: null
video_choice: Image
v2_service_title: Campaign
v2_service_content: 'Last night, within about 30 minutes, you watched a bit of TV, checked your phone’s news feed, watched a cat video your mum sent you and searched for a birthday present for your brother. So how the hell are you supposed to grab the attention span of customers who don’t have one?'
v2_left_list:
  - 'Campaign Planning'
  - 'Media Management'
  - 'Social Media'
  - 'Out of Home'
  - 'Campaign idea creation'
v2_right_list:
  - Radio
  - 'Digital Display'
  - Print
  - Search
  - 'Asset creation'
v2_service_image:
  - 3-BAE.jpg
v2_service_button_label: 'Click Here'
hero_text: Campaigns
hero_intro: 'Let’s not be delicate about it, selling is what a marketing campaign is designed to do. And when the world is this bloomin’ noisy, that’s no mean feat. So how are you going to do it?'
content_grid:
  -
    content_title: 'Integrated campaigns'
    content_text: 'When no one is focused on anything for too long you can’t expect one ad in one place to hit home. So if you want to make a big noise, it’s not just what you say and how you say it. It’s where you say it that counts. That’s the beauty of an integrated campaign with Think!. Yes, your ad zings like a lemon on steroids, but it also targets your customers like a sniper and zeroes in on them wherever they are – online, in print, in app or by email. And the more impressions you make, the more of an…er… impression you make. Grab their attention.'
    content_image: 3-BAE.jpg
    content_link_text: 'Start by grabbing ours'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: 'Brand campaigns'
    content_text: |-
      Your brand has the power to stir the emotions, to stimulate the feels and to take up residence in your customers’ heads. And there’s you thinking you just made ‘stuff’. Tch.
      A brand campaign is a slower burn, designed to let your brand drip, drip, drip into the memory. Take Apple. Sometimes they’ll run a campaign advertising the latest iPhone. But sometimes they’ll run a campaign that has no ambition other than to make you think ‘wow, Apple’. How do they do that? They do it by sharing values. By tapping into deep emotion. By making you feel.
    content_image: 3-BAE.jpg
    content_link_text: 'We’d like to show you how'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: 'Conversion campaigns'
    content_text: 'We promise not to get all nerdy about this, but there are two types of campaign. One is the long term brand builder. But equally important is the short term, ‘here’s our product/service, buy it now’ sort of campaign. This is all about getting your customer to do something. For that, you’ll need messages and offers that get them over the line. Whether that’s via digital display, search, or something that hasn’t been invented yet - we’ve got you covered.'
    content_image: 3-BAE.jpg
    content_link_text: 'Get converting today'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
  -
    content_title: 'Creative Concepts'
    content_text: 'Mail’s arrived. On your desk right now are some brown envelopes you really don’t want to open, the odd brochure, and a bit of junk mail that may as well have ‘bin’ written in big letters on it. Your inbox and social feeds are the same. Lots of offers you skip. Lots of ads you ignore. But what’s this? Something clever. Something that makes you laugh or say, ‘I’ve never seen that before’. Something that gets your fingers tapping, clicking or unfolding. That’s the result we’re after. It’s the ad that grabs. It’s the poster or banner on the bus stop, bridge or building. It’s the box you package your products in that’s says, ‘this really is worth paying a premium for’. That’s creative concepts at Think!Creative.'
    content_image: 3-BAE.jpg
    content_link_text: 'Attention please'
    content_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
call_to_action: 'Need a campaign that gets things moving? Let us know!'
handle_text: 'Let’s Think! together'
where_do_i_go: 4
cta_button: 'Contact us'
cta_link: 'entry::245b90b3-1382-45b2-8ea4-5ab7469ea872'
