title: Services
template: services/show
layout: layout
mount: 4b041b66-7921-4307-99a0-2aaecb2d2504
taxonomies:
  - core
revisions: false
route: '/services/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
