title: Services
sections:
  main:
    display: Main
    fields:
      -
        import: services_page
        config:
          title:
            required: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - services
          max_items: 1
          listable: false
          localizable: true
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: core
        field:
          type: terms
          taxonomies:
            - core
          display: 'Core Services'
          mode: select
  SEO:
    display: SEO
    fields:
      -
        handle: seo
        field:
          type: seo_pro
          listable: false
          display: SEO
